// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjlmrylxkxcetxzdzgws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqbG1yeWx4a3hjZXR4emR6Z3dzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5Mzg4MDcsImV4cCI6MjA1NzUxNDgwN30.6vd2yBC8gLylUKItyecqKcOEa7s9R2p7XBkNuwBGB-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);